export const USER_SUPPORT_LIST_REQUEST = "USER_SUPPORT_LIST_REQUEST";
export const USER_SUPPORT_LIST_SUCCESS = "USER_SUPPORT_LIST_SUCCESS";
export const USER_SUPPORT_LIST_FAIL = "USER_SUPPORT_LIST_FAIL";
